<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>be.rk22</groupId>
        <artifactId>proc-debugger-nb-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>proc-debugger-nb-standalone</artifactId>
    <packaging>jar</packaging>
    <name>MariaDB Procedure Debugger - Standalone</name>

    <dependencies>
        <dependency>
            <groupId>be.rk22</groupId>
            <artifactId>proc-debugger-nb-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>21.0.2</version>
            <classifier>win</classifier>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-base</artifactId>
            <version>21.0.2</version>
            <classifier>win</classifier>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>21.0.2</version>
            <classifier>win</classifier>
        </dependency>

        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.5.3</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <configuration>
                    <mainClass>be.rk22.dbgplugin.standalone.App</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
